#define SHALLOW_THREAD_NUM 32
#pragma kernel initTallCellGrid

float3 Min;
float CellLength;
float SeaLevel;
uint2 XZResolution;
uint ConstantCellNum;

Texture2D<float> TerrianTexture_R;
SamplerState Sampler_Trilinear_Clamp;

RWTexture2D<float> TerrianHeight_RW;
RWTexture2D<float> TallCellHeight_RW;
RWTexture3D<float3> Velocity_RW;

[numthreads(SHALLOW_THREAD_NUM, SHALLOW_THREAD_NUM, 1)]
void initTallCellGridFineLevel(uint3 id : SV_DispatchThreadID)
{
    if (any(id.xy) > XZResolution)
        return;
    
    float2 UV = id.xy / (float2) XZResolution;
    float TerrianHeight = TerrianTexture_R.SampleLevel(Sampler_Trilinear_Clamp, UV, 0);
    TerrianHeight_RW[id.xy] = TerrianHeight;
}